matrix:
- name: yaml
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - 'cocktails/***.yaml'
  default_encoding: utf-8