name: Yaml Lint
on: [push]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      config_data: "{extends: default, rules: {new-line-at-end-of-file: disable}}"
      with:
        file_or_dir: cocktails/