name: Yaml Lint
on:
  pull_request:
    branches: [ main ]
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: cocktails/
        config_file: .yamllint.yaml
